# Generated by Django 4.2.13 on 2024-05-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
